In [2]:
import pandas as pd

In [3]:
df_results = pd.read_csv('evolutionary_experiment_results.csv')
df_results

,Experiment,Best Fitness,Mean Fitness,Median Fitness,Worst Fitness,Standard Deviation,Number of Unique Individuals,Number of Feasible Individuals,Number of Infeasible Individuals,Best Individual,Constraints
0,1,6348.455273,6630.199088,6392.993844,14368.049245,762.749657,196,922,78,[ 1.02045365 0.51380648 52.65006835 79.01391978],"[-0.004307334832857279, -0.011524828223080985,..."
1,2,6321.649827,6896.169180,6346.369956,43897.931827,2051.051419,214,916,84,[ 1.02045365 0.51380648 52.79656201 77.60802913],"[-0.0014800071458949127, -0.010127278682478869..."
2,3,6296.680425,6927.358737,6350.122208,26558.390808,1752.778295,234,927,73,[ 1.03099708 0.51380648 53.21294165 75.05646309],"[-0.003987303849176005, -0.0061550168812571915..."
3,4,6271.883637,6802.008618,6300.090747,27473.506085,1638.077067,226,927,73,[ 1.03099708 0.51380648 53.40436534 73.52695492],"[-0.00029282659866902705, -0.00432883486209467..."
4,5,6272.316925,7056.820270,6308.744342,34525.416510,2639.191304,195,915,85,[ 1.03099708 0.51380648 53.36321276 73.72045202],"[-0.0010870714356072675, -0.004721430496519185..."
...,...,...,...,...,...,...,...,...,...,...,...
95,96,6267.577837,6506.926821,6272.692884,11775.250779,507.144663,167,917,83,[ 1.03100637 0.51748925 53.41714607 73.35234562],"[-5.545279918650614e-05, -0.00788967177399058,..."
96,97,6267.577837,6482.981290,6276.906155,10772.927185,466.464706,170,893,107,[ 1.03100637 0.52246812 53.41714607 73.35234562],"[-5.545279918650614e-05, -0.01286854981082497,..."
97,98,6267.577837,6611.881491,6267.577837,19515.029826,946.919857,174,915,85,[ 1.03100637 0.53049708 53.41714607 73.35234562],"[-5.545279918650614e-05, -0.020897508377498597..."
98,99,6267.577837,6672.138364,6276.242304,16097.707704,947.228689,180,912,88,[ 1.03100637 0.51326698 53.41714607 73.35234562],"[-5.545279918650614e-05, -0.003667401687013627..."
99,100,6267.577837,6601.219358,6273.239302,24184.327447,1060.035580,167,907,93,[ 1.03100637 0.52809084 53.41714607 73.35234562],"[-5.545279918650614e-05, -0.01849126200575668,..."

In [4]:
# Best Fitness	Mean Fitness	Median Fitness	Worst Fitness	Standard Deviation	Number of Unique Individuals	Number of Feasible Individuals	Number of Infeasible Individuals
ls_measures_cols = ['Best Fitness', 'Mean Fitness', 'Median Fitness', 'Worst Fitness', 'Standard Deviation', 'Number of Unique Individuals', 'Number of Feasible Individuals', 'Number of Infeasible Individuals']
df_results[ls_measures_cols].describe()

,Best Fitness,Mean Fitness,Median Fitness,Worst Fitness,Standard Deviation,Number of Unique Individuals,Number of Feasible Individuals,Number of Infeasible Individuals
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000
mean,6269.391921,6559.106324,6275.366888,16241.118114,768.495164,170.49000,905.700000,94.300000
std,10.070696,141.673760,17.565379,10087.467842,553.870341,19.99924,15.184056,15.184056
min,6267.577837,6432.166924,6267.577837,9523.676902,370.297452,120.00000,855.000000,65.000000
25%,6267.577837,6490.596264,6267.578242,11198.530442,500.507257,158.00000,897.000000,84.750000
50%,6267.578242,6525.547861,6270.705037,12657.852443,591.242243,169.50000,908.000000,92.000000
75%,6267.578242,6559.386658,6274.947346,16300.292060,757.923793,180.25000,915.250000,103.000000
max,6348.455273,7201.651442,6392.993844,72720.994642,3582.939653,234.00000,935.000000,145.000000